version: '3.7'

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
       - /src/node_modules
  deploy:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: aws s3 sync /dist s3://clickworker-pfe.1715labs.com
